<a href="https://colab.research.google.com/github/Sri-Tej/sri/blob/master/Numpy_sritej.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
np.zeros([3, 2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.add([1,2,3],[1,4,5])

array([2, 6, 8])

In [ ]:
np.subtract([9,9,6],[4,4,4])

array([5, 5, 2])

In [ ]:
np.multiply([1,2,3],[6,7,7])

array([ 6, 14, 21])

In [ ]:
np.ones([2,1])

array([[1.],
       [1.]])

In [ ]:
np.eye(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [20]:
x = np.array([1,2,3])